# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created: Wed May 22 23:18:33 2013
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(986, 762)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("resources/favicon.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.viewNotifications = QtGui.QTableView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewNotifications.sizePolicy().hasHeightForWidth())
        self.viewNotifications.setSizePolicy(sizePolicy)
        self.viewNotifications.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.viewNotifications.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.viewNotifications.setShowGrid(True)
        self.viewNotifications.setObjectName(_fromUtf8("viewNotifications"))
        self.viewNotifications.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.viewNotifications)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.notificationTabs = QtGui.QTabWidget(self.centralwidget)
        self.notificationTabs.setEnabled(True)
        self.notificationTabs.setMovable(True)
        self.notificationTabs.setObjectName(_fromUtf8("notificationTabs"))
        self.detailsTab = QtGui.QWidget()
        self.detailsTab.setObjectName(_fromUtf8("detailsTab"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.detailsTab)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.viewDetails = QtGui.QTableView(self.detailsTab)
        self.viewDetails.setObjectName(_fromUtf8("viewDetails"))
        self.viewDetails.horizontalHeader().setVisible(False)
        self.viewDetails.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout_2.addWidget(self.viewDetails)
        self.notificationTabs.addTab(self.detailsTab, _fromUtf8(""))
        self.backtraceTab = QtGui.QWidget()
        self.backtraceTab.setObjectName(_fromUtf8("backtraceTab"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.backtraceTab)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.viewBacktrace = QtGui.QTextEdit(self.backtraceTab)
        self.viewBacktrace.setObjectName(_fromUtf8("viewBacktrace"))
        self.horizontalLayout.addWidget(self.viewBacktrace)
        self.notificationTabs.addTab(self.backtraceTab, _fromUtf8(""))
        self.getTab = QtGui.QWidget()
        self.getTab.setObjectName(_fromUtf8("getTab"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.getTab)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.viewGet = QtGui.QTreeView(self.getTab)
        self.viewGet.setAlternatingRowColors(True)
        self.viewGet.setObjectName(_fromUtf8("viewGet"))
        self.horizontalLayout_3.addWidget(self.viewGet)
        self.notificationTabs.addTab(self.getTab, _fromUtf8(""))
        self.postTab = QtGui.QWidget()
        self.postTab.setObjectName(_fromUtf8("postTab"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.postTab)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.viewPost = QtGui.QTreeView(self.postTab)
        self.viewPost.setAlternatingRowColors(True)
        self.viewPost.setObjectName(_fromUtf8("viewPost"))
        self.horizontalLayout_4.addWidget(self.viewPost)
        self.notificationTabs.addTab(self.postTab, _fromUtf8(""))
        self.serverTab = QtGui.QWidget()
        self.serverTab.setObjectName(_fromUtf8("serverTab"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.serverTab)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.viewServer = QtGui.QTreeView(self.serverTab)
        self.viewServer.setAlternatingRowColors(True)
        self.viewServer.setHeaderHidden(True)
        self.viewServer.setObjectName(_fromUtf8("viewServer"))
        self.horizontalLayout_5.addWidget(self.viewServer)
        self.notificationTabs.addTab(self.serverTab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.notificationTabs)
        if bool(MainWindow.settings.show_debugger):
            self.label = QtGui.QLabel(self.centralwidget)
            self.label.setObjectName(_fromUtf8("label"))
            self.verticalLayout.addWidget(self.label)
            self.processMonitor = QtGui.QPlainTextEdit(self.centralwidget)
            self.processMonitor.setObjectName(_fromUtf8("processMonitor"))
            self.verticalLayout.addWidget(self.processMonitor)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setEnabled(True)
        self.toolBar.setMovable(False)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionSettings = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("resources/gear.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSettings.setIcon(icon1)
        self.actionSettings.setObjectName(_fromUtf8("actionSettings"))
        self.actionClose = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("resources/exit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClose.setIcon(icon2)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.toolBar.addAction(self.actionSettings)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionClose)

        self.retranslateUi(MainWindow)
        self.notificationTabs.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Webiny Notifier", None, QtGui.QApplication.UnicodeUTF8))
        self.notificationTabs.setTabText(self.notificationTabs.indexOf(self.detailsTab), QtGui.QApplication.translate("MainWindow", "Details", None, QtGui.QApplication.UnicodeUTF8))
        self.viewBacktrace.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.notificationTabs.setTabText(self.notificationTabs.indexOf(self.backtraceTab), QtGui.QApplication.translate("MainWindow", "Backtrace", None, QtGui.QApplication.UnicodeUTF8))
        self.notificationTabs.setTabText(self.notificationTabs.indexOf(self.getTab), QtGui.QApplication.translate("MainWindow", "GET", None, QtGui.QApplication.UnicodeUTF8))
        self.notificationTabs.setTabText(self.notificationTabs.indexOf(self.postTab), QtGui.QApplication.translate("MainWindow", "POST", None, QtGui.QApplication.UnicodeUTF8))
        self.notificationTabs.setTabText(self.notificationTabs.indexOf(self.serverTab), QtGui.QApplication.translate("MainWindow", "SERVER", None, QtGui.QApplication.UnicodeUTF8))
        if bool(MainWindow.settings.show_debugger):
            self.label.setText(QtGui.QApplication.translate("MainWindow", "Process monitor:", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSettings.setText(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSettings.setToolTip(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setText(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setToolTip(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))

