<script type="text/javascript">
    var THEME = '{$viewObject.themeWebPath}';
    var WEB = '{$viewObject.webPath}';
</script>

{minify type="css"}
    kendo.common.min.css,
    kendo.default.min.css,
    font-awesome.min.css,
    main.css,
    toolbar.css,
    widget.css,
    widgets/textWidget.css,
    widgets/mapWidget.css,
    widgets/twitterWidget.css,
    widgets/videoWidget.css,
    widgets/linkWidget.css
{/minify}

{minify type="js"}
    jquery-1.8.3.js,
    jquery-ui-1.9.2.custom.js,
    mouseEvent.js,
    jQueryFix.js,
    webyDrag.js,
    weby.js,
    app.js,
    appToolbar.js,
    baseTool.js,
    baseWidget.js,
    baseParser.js,
    baseIframeWidget.js,
    tools/textTool.js,
    tools/mapTool.js,
    tools/instagramTool.js,
    tools/facebookTool.js,
    tools/videoTool.js,
    tools/preziTool.js,
    tools/slideShareTool.js,
    tools/googleDriveTool.js,
    tools/skyDriveTool.js,
    tools/soundCloudTool.js,
    tools/twitterTool.js,
    tools/linkedInTool.js,
    tools/linkTool.js,
    tools/vineTool.js,
    tools/pinterestTool.js,
    widgets/textWidget.js,
    widgets/mapWidget.js,
    widgets/facebookWidget.js,
    widgets/instagramWidget.js,
    widgets/videoWidget.js,
    widgets/preziWidget.js,
    widgets/slideShareWidget.js,
    widgets/googleDriveWidget.js,
    widgets/skyDriveWidget.js,
    widgets/soundCloudWidget.js,
    widgets/twitterWidget.js,
    widgets/linkedinWidget.js,
    widgets/linkWidget.js,
    widgets/vineWidget.js,
    widgets/pinterestWidget.js,
    parsers/videoParser.js,
    parsers/linkedInParser.js,
    parsers/preziParser.js,
    parsers/slideShareParser.js,
    parsers/skyDriveParser.js,
    parsers/instagramParser.js,
    parsers/facebookParser.js,
    parsers/googleDriveParser.js,
    parsers/soundCloudParser.js,
    parsers/twitterParser.js,
    parsers/vineParser.js,
    parsers/linkParser.js,
    parsers/pinterestParser.js,
    init.js
{/minify}
